from Bio.SeqUtils.ProtParam import ProteinAnalysis

# DSUP protein sequence
dsup_seq = (
    "MASTHQSSTEPSSTGKSEETKKDASQGSGQDSKNVTVTKGTGSSATSAAIVKTGGSQGKDSSTTAGSSST"
    "QGQKFSTTPTDPKTFSSDQKEKSKSPAKEVPSGGDSKSQGDTKSQSDAKSSGQSQGQSKDSGKSSSDSSK"
    "SHSVIGAVKDVVAGAKDVAGKAVEDAPSIMHTAVDAVKNAATTVKDVASSAASTVAEKVVDAYHSVVGDK"
    "TDDKKEGEHSGDKKDDSKAGSGSGQGGDNKKSEGETSGQAESSSGNEGAAPAKGRGRGRPPAAAKGVAKG"
    "AAKGAAASKGAKSGAESSKGGEQSSGDIEMADASSKGGSDQRDSAATVGEGGASGSEGGAKKGRGRGAGK"
    "KADAGDTSAEPPRRSSRLTSSGTGAGSAPAAAKGGAKRAASSSSTPSNAKKQATGGAGKAAATKATAAKS"
    "AASKAPQNGAGAKKKGGKAGGRKRK"
)

# Analyze protein sequence
dsup_analysis = ProteinAnalysis(dsup_seq)

# Calculate isoelectric point (pI)
dsup_pI = dsup_analysis.isoelectric_point()

print("Isoelectric point (pI) of DSUP:", dsup_pI)
